//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProdContact
{
    using System;
    using System.Collections.Generic;
    
    public partial class AIGeneratedPrompt
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AIGeneratedPrompt()
        {
            this.AIGeneratedScripts = new HashSet<AIGeneratedScript>();
        }
    
        public int ID { get; set; }
        public Nullable<int> SceneId { get; set; }
        public Nullable<int> LanguageId { get; set; }
        public Nullable<int> SceneLocationId { get; set; }
        public string AIPromp { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string CreatedBy { get; set; }
        public bool IsActive { get; set; }
    
        public virtual Language Language { get; set; }
        public virtual Scene Scene { get; set; }
        public virtual SceneLocation SceneLocation { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AIGeneratedScript> AIGeneratedScripts { get; set; }
    }
}
