//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProdContact
{
    using System;
    using System.Collections.Generic;
    
    public partial class LogRecord
    {
        public int ID { get; set; }
        public Nullable<int> RecordID { get; set; }
        public string ActionOnForm { get; set; }
        public string ActionTaken { get; set; }
        public string ActionBy { get; set; }
        public Nullable<System.DateTime> ActionOn { get; set; }
        public string StrRecordID { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
    }
}
