//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProdContact
{
    using System;
    using System.Collections.Generic;
    
    public partial class OneLinerWriterScript
    {
        public int Id { get; set; }
        public int OneLinerScriptID { get; set; }
        public byte[] ScriptFile { get; set; }
        public string UploadedBy { get; set; }
        public Nullable<bool> IsApproved { get; set; }
        public string ApprovedBy { get; set; }
        public Nullable<System.DateTime> ApprovedOn { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual OneLinerScript OneLinerScript { get; set; }
    }
}
