//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProdContact
{
    using System;
    using System.Collections.Generic;
    
    public partial class OneLinerStart
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public OneLinerStart()
        {
            this.OneLiners = new HashSet<OneLiner>();
            this.OneLinerStartDetails = new HashSet<OneLinerStartDetail>();
        }
    
        public int Id { get; set; }
        public string ContentHead { get; set; }
        public string Remarks { get; set; }
        public string EmailSubject { get; set; }
        public string EmailBody { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OneLiner> OneLiners { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OneLinerStartDetail> OneLinerStartDetails { get; set; }
    }
}
