//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProdContact
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProjectCrewContract
    {
        public int ID { get; set; }
        public Nullable<int> ProjectID { get; set; }
        public Nullable<int> TeamMemberID { get; set; }
        public Nullable<int> ContractTypeID { get; set; }
        public Nullable<decimal> PayScale { get; set; }
    
        public virtual ContractType ContractType { get; set; }
        public virtual Project Project { get; set; }
        public virtual TeamMember TeamMember { get; set; }
    }
}
