//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProdContact
{
    using System;
    using System.Collections.Generic;
    
    public partial class Project
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Project()
        {
            this.PaymentRequestHeads = new HashSet<PaymentRequestHead>();
            this.ProjectBudgets = new HashSet<ProjectBudget>();
            this.ProjectCasts = new HashSet<ProjectCast>();
            this.ProjectCrewContracts = new HashSet<ProjectCrewContract>();
            this.ProjectEpisodes = new HashSet<ProjectEpisode>();
            this.ProjectSchedulings = new HashSet<ProjectScheduling>();
            this.ProjectTeamMembers = new HashSet<ProjectTeamMember>();
            this.Scenes = new HashSet<Scene>();
            this.SetLocations = new HashSet<SetLocation>();
            this.TeamExpenses = new HashSet<TeamExpense>();
        }
    
        public int ProjectId { get; set; }
        public string ProjectName { get; set; }
        public string Code { get; set; }
        public Nullable<int> GenreId { get; set; }
        public Nullable<int> ProjectFrequencyId { get; set; }
        public Nullable<int> LocationId { get; set; }
        public Nullable<int> TotalEpisodes { get; set; }
        public Nullable<int> TimeDuration { get; set; }
        public string TimeUnit { get; set; }
        public Nullable<int> ManagerId { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public Nullable<int> ProjectTypeId { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<decimal> Budget { get; set; }
        public Nullable<int> DirectorID { get; set; }
        public Nullable<int> HOPID { get; set; }
        public Nullable<int> OneLinerID { get; set; }
    
        public virtual Location Location { get; set; }
        public virtual OneLiner OneLiner { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PaymentRequestHead> PaymentRequestHeads { get; set; }
        public virtual ProjectFrequency ProjectFrequency { get; set; }
        public virtual ProjectType ProjectType { get; set; }
        public virtual TeamMember TeamMember { get; set; }
        public virtual TeamMember TeamMember1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProjectBudget> ProjectBudgets { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProjectCast> ProjectCasts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProjectCrewContract> ProjectCrewContracts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProjectEpisode> ProjectEpisodes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProjectScheduling> ProjectSchedulings { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProjectTeamMember> ProjectTeamMembers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Scene> Scenes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SetLocation> SetLocations { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TeamExpense> TeamExpenses { get; set; }
    }
}
