//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProdContact
{
    using System;
    using System.Collections.Generic;
    
    public partial class SceneCharacter
    {
        public int ID { get; set; }
        public Nullable<int> SceneId { get; set; }
        public Nullable<int> CastId { get; set; }
        public Nullable<bool> IsActive { get; set; }
    
        public virtual ProjectCast ProjectCast { get; set; }
        public virtual Scene Scene { get; set; }
    }
}
