//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProdContact
{
    using System;
    using System.Collections.Generic;
    
    public partial class SceneWardrobe
    {
        public int ID { get; set; }
        public int SceneId { get; set; }
        public int CastID { get; set; }
        public int WardrobeID { get; set; }
        public Nullable<int> WardrobeStylistId { get; set; }
        public Nullable<int> MakeupArtistId { get; set; }
        public bool IsActive { get; set; }
        public string Remarks { get; set; }
    
        public virtual ProjectCast ProjectCast { get; set; }
        public virtual Scene Scene { get; set; }
        public virtual TeamMember TeamMember { get; set; }
        public virtual TeamMember TeamMember1 { get; set; }
        public virtual Wardrobe Wardrobe { get; set; }
    }
}
