//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProdContact
{
    using System;
    using System.Collections.Generic;
    
    public partial class Scene
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Scene()
        {
            this.AIGeneratedPrompts = new HashSet<AIGeneratedPrompt>();
            this.IssueDelayLogs = new HashSet<IssueDelayLog>();
            this.SceneCharacters = new HashSet<SceneCharacter>();
            this.SceneProps = new HashSet<SceneProp>();
            this.ScheduledScenes = new HashSet<ScheduledScene>();
            this.SceneWardrobes = new HashSet<SceneWardrobe>();
        }
    
        public int SceneId { get; set; }
        public string SceneName { get; set; }
        public int ProjectId { get; set; }
        public int EpisodeId { get; set; }
        public Nullable<int> LocationId { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public string Remarks { get; set; }
        public string Synopsis { get; set; }
        public string DayTime { get; set; }
        public string SoundEffect { get; set; }
        public string BackgroundPlay { get; set; }
        public Nullable<bool> isFlashBack { get; set; }
        public Nullable<bool> isSceneCut { get; set; }
        public Nullable<bool> isPhoneTalk { get; set; }
        public Nullable<bool> isReShoot { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AIGeneratedPrompt> AIGeneratedPrompts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IssueDelayLog> IssueDelayLogs { get; set; }
        public virtual Project Project { get; set; }
        public virtual ProjectEpisode ProjectEpisode { get; set; }
        public virtual SceneLocation SceneLocation { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SceneCharacter> SceneCharacters { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SceneProp> SceneProps { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ScheduledScene> ScheduledScenes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SceneWardrobe> SceneWardrobes { get; set; }
    }
}
