//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProdContact
{
    using System;
    using System.Collections.Generic;
    
    public partial class SetLocationTeamMember
    {
        public int ID { get; set; }
        public int MemberID { get; set; }
        public int SetLocationID { get; set; }
        public bool IsActive { get; set; }
        public System.DateTime CreationDate { get; set; }
        public string CreationBy { get; set; }
    
        public virtual SetLocation SetLocation { get; set; }
    }
}
