//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProdContact
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblAgency
    {
        public int AgencyId { get; set; }
        public string Name { get; set; }
        public string Code { get; set; }
        public Nullable<int> AgencyCategoryId { get; set; }
        public Nullable<int> AgencyTypeId { get; set; }
        public string HeadOfficeAddress { get; set; }
        public Nullable<int> HeadOfficeCityId { get; set; }
        public Nullable<int> HeadOfficeStateId { get; set; }
        public string HeadOfficePhone { get; set; }
        public string HeadOfficeFax { get; set; }
        public string HeadOfficeEmailAddress { get; set; }
        public string BranchOfficeAddress { get; set; }
        public Nullable<int> BranchOffice1CityId { get; set; }
        public Nullable<int> BranchOffice1StateId { get; set; }
        public string BranchOffice1Phone { get; set; }
        public string BranchOffice1Fax { get; set; }
        public string BranchOffice1EmailAddress { get; set; }
        public Nullable<int> BranchOffice2CityId { get; set; }
        public Nullable<int> BranchOffice2StateId { get; set; }
        public string BranchOffice2Phone { get; set; }
        public string BranchOffice2Fax { get; set; }
        public string BranchOffice2EmailAddress { get; set; }
        public string FinanceContactPerson { get; set; }
        public string FinancePersonDesignation { get; set; }
        public string FinanceDirectPhone { get; set; }
        public string FinanceMobile { get; set; }
        public string FinanceFax { get; set; }
        public string FinanceEmailAddress { get; set; }
        public string MediaContactPerson { get; set; }
        public string MediaPersonDesignation { get; set; }
        public string MediaDirectPhone { get; set; }
        public string MediaMobile { get; set; }
        public string MediaFax { get; set; }
        public string MediaEmailAddress { get; set; }
        public Nullable<System.DateTime> BusinessCommencementDate { get; set; }
        public string NTNNo { get; set; }
        public string AgencyStatus { get; set; }
        public Nullable<int> AgencyLegalStatus { get; set; }
        public string BankingWith1 { get; set; }
        public string Branch1 { get; set; }
        public string AccountNo1 { get; set; }
        public Nullable<decimal> AvgMonthlyBill { get; set; }
        public string BankingWith2 { get; set; }
        public string Branch2 { get; set; }
        public string AccountNo2 { get; set; }
        public Nullable<decimal> AvgMonthlyBill2 { get; set; }
        public Nullable<decimal> CreditApplied { get; set; }
        public Nullable<int> CreditAppliedDays { get; set; }
        public Nullable<int> PaymentMode { get; set; }
        public string PaymentNumber { get; set; }
        public string PaymentNote { get; set; }
        public Nullable<decimal> CreditApproved { get; set; }
        public Nullable<int> CreditApprovedDays { get; set; }
        public Nullable<bool> NicCopy { get; set; }
        public string NicCopyPath { get; set; }
        public Nullable<bool> NTNCertificateCopy { get; set; }
        public string NTNCertificatePath { get; set; }
        public Nullable<bool> BankStatement { get; set; }
        public string BankStatementPath { get; set; }
        public Nullable<bool> ClientsList { get; set; }
        public string ClientsListPath { get; set; }
        public Nullable<bool> Form29 { get; set; }
        public string Form29Path { get; set; }
        public Nullable<bool> ReportVisitOffice { get; set; }
        public string AgencyGSTNo { get; set; }
        public Nullable<bool> PresentStatus { get; set; }
        public Nullable<decimal> OutstandingPKR { get; set; }
        public Nullable<decimal> OverDuePKR { get; set; }
        public Nullable<int> OverDueDays { get; set; }
        public Nullable<decimal> LastPaymentRecieved { get; set; }
        public Nullable<System.DateTime> PaidOn { get; set; }
        public Nullable<decimal> DishonorChequeAmt { get; set; }
        public string DishonorChequeNo { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public string CreatedByDesignation { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<bool> IsApproved { get; set; }
        public Nullable<int> ApprovedBy { get; set; }
        public string ApprovedByDesignation { get; set; }
        public Nullable<System.DateTime> ApprovedDate { get; set; }
        public Nullable<System.DateTime> LastModifiedDate { get; set; }
        public Nullable<int> LastModifiedBy { get; set; }
        public Nullable<bool> IsCR { get; set; }
        public Nullable<bool> IsRegistered { get; set; }
        public bool IsActive { get; set; }
        public Nullable<int> PaymentType { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public Nullable<int> ChannelId { get; set; }
        public Nullable<decimal> MasterAgencyID { get; set; }
    }
}
