//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProdContact
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblChannel
    {
        public int ChannelId { get; set; }
        public string Name { get; set; }
        public string Code { get; set; }
        public Nullable<int> CompanyId { get; set; }
        public bool IsActive { get; set; }
        public string Prefix { get; set; }
        public Nullable<int> GLPublication { get; set; }
        public string PrefixNew { get; set; }
    }
}
