//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Altodownloading
{
    using System;
    using System.Collections.Generic;
    
    public partial class ArchiveFileDetail
    {
        public int ID { get; set; }
        public int ArchiveID { get; set; }
        public string FileTypeStatus { get; set; }
        public string FileFullPath { get; set; }
        public string FileDuration { get; set; }
        public Nullable<decimal> vFileSize { get; set; }
        public Nullable<bool> IsCopied { get; set; }
        public Nullable<short> PriorityOrder { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<System.DateTime> CopiedOn { get; set; }
        public string SourcePath { get; set; }
        public bool InProcess { get; set; }
        public string BaseStation { get; set; }
    }
}
