//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Altodownloading
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChannelCategory
    {
        public ChannelCategory()
        {
            this.ChannelCategoryDetails = new HashSet<ChannelCategoryDetail>();
        }
    
        public int ID { get; set; }
        public string CatagoryName { get; set; }
        public bool IsActive { get; set; }
        public string CatShortName { get; set; }
    
        public virtual ICollection<ChannelCategoryDetail> ChannelCategoryDetails { get; set; }
    }
}
