//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Altodownloading
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChannelCategoryDetail
    {
        public int ID { get; set; }
        public int CategoryID { get; set; }
        public int ChannelID { get; set; }
        public bool IsActive { get; set; }
    
        public virtual ChannelCategory ChannelCategory { get; set; }
        public virtual tblChannel tblChannel { get; set; }
    }
}
