//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Altodownloading
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblArchive
    {
        public long ArchiveID { get; set; }
        public Nullable<long> MediaNo { get; set; }
        public Nullable<int> ChannelID { get; set; }
        public Nullable<int> CategoryID { get; set; }
        public Nullable<int> MediaTypeID { get; set; }
        public Nullable<int> ClassificationID { get; set; }
        public Nullable<System.DateTime> EntryDate { get; set; }
        public Nullable<System.DateTime> ShootDate { get; set; }
        public Nullable<int> SourceID { get; set; }
        public Nullable<int> FootageTypeID { get; set; }
        public string FileName { get; set; }
        public string JTSFileName { get; set; }
        public string JTSTicketNo { get; set; }
        public Nullable<int> JTSReporterID { get; set; }
        public Nullable<int> JTSCameramanID { get; set; }
        public Nullable<int> JTSBureau { get; set; }
        public string JTSJobType { get; set; }
        public string JTSCreatedBy { get; set; }
        public string JTSSlug { get; set; }
        public string JTSDuration { get; set; }
        public string RackNo { get; set; }
        public string ShelfNo { get; set; }
        public Nullable<int> ProducerID { get; set; }
        public string Director { get; set; }
        public string Singer_Band { get; set; }
        public string Duration { get; set; }
        public string ProgrammeTitleOrName { get; set; }
        public string ProgramGenre_Lyrics { get; set; }
        public string SubTitleOrCaption_Cast { get; set; }
        public Nullable<System.DateTime> TelecastDate { get; set; }
        public Nullable<int> Midbreaks { get; set; }
        public string EpisodeNo { get; set; }
        public string Writer { get; set; }
        public string NOCNo { get; set; }
        public Nullable<int> LanguageID { get; set; }
        public string Theme { get; set; }
        public string Remarks { get; set; }
        public string Album { get; set; }
        public string Origin { get; set; }
        public string FootageDetail { get; set; }
        public string Client { get; set; }
        public Nullable<System.DateTime> Cdate { get; set; }
        public Nullable<System.DateTime> CTime { get; set; }
        public string SeaChangeCode { get; set; }
        public Nullable<int> MediaStatusID { get; set; }
        public Nullable<int> InputTypeID { get; set; }
        public Nullable<decimal> TotalCapacity { get; set; }
        public Nullable<decimal> CapacityUtilized { get; set; }
        public Nullable<decimal> CapacityAvailable { get; set; }
        public string DVDTitle { get; set; }
        public Nullable<bool> IsHighClip { get; set; }
        public Nullable<bool> IsLowClip { get; set; }
        public Nullable<long> DVDNo { get; set; }
        public Nullable<bool> IsIssued { get; set; }
        public Nullable<long> OnsiteBackup { get; set; }
        public Nullable<long> OffsiteBackup { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<int> EditedBy { get; set; }
        public Nullable<System.DateTime> EditedOn { get; set; }
        public string PartNo { get; set; }
        public Nullable<int> OnsiteMediaTypeId { get; set; }
        public Nullable<int> OffsiteMediaTypeId { get; set; }
        public Nullable<int> DepartmentId { get; set; }
        public Nullable<int> PhotographerId { get; set; }
        public System.Guid rowguid { get; set; }
        public Nullable<int> BureauTape { get; set; }
        public Nullable<int> AnchorId { get; set; }
        public Nullable<short> MediaSource { get; set; }
        public Nullable<bool> IsInternational { get; set; }
        public string BaseStationID { get; set; }
        public Nullable<bool> IsMasterCopy { get; set; }
        public Nullable<int> ProgramTitleID { get; set; }
        public Nullable<bool> MarkDeleted { get; set; }
        public Nullable<int> ContentTypeID { get; set; }
        public Nullable<int> ChannelCategoryID { get; set; }
    }
}
