//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Altodownloading
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblChannel
    {
        public tblChannel()
        {
            this.ChannelCategoryDetails = new HashSet<ChannelCategoryDetail>();
        }
    
        public int ChannelId { get; set; }
        public string Name { get; set; }
        public int LanguageId { get; set; }
        public Nullable<int> CreatedByUserId { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<int> LastModifiedByUserId { get; set; }
        public Nullable<System.DateTime> LastModifiedOn { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public System.Guid rowguid { get; set; }
        public string ChannelPath { get; set; }
        public Nullable<int> orderbyID { get; set; }
    
        public virtual ICollection<ChannelCategoryDetail> ChannelCategoryDetails { get; set; }
    }
}
