//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExpressDigital
{
    using System;
    using System.Collections.Generic;
    
    public partial class Adjustment
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Adjustment()
        {
            this.AdjustmentDetails = new HashSet<AdjustmentDetail>();
            this.CRVCN__ = new HashSet<CRVCN__>();
            this.InvDNs = new HashSet<InvDN>();
            this.LedgerBalances = new HashSet<LedgerBalance>();
            this.LSAdjustmentDetails = new HashSet<LSAdjustmentDetail>();
        }
    
        public int ID { get; set; }
        public string AdjustmentNo { get; set; }
        public bool IsDebitNote { get; set; }
        public int AgencyId { get; set; }
        public int ClientId { get; set; }
        public Nullable<int> PortalID { get; set; }
        public int InvoiceId { get; set; }
        public decimal Gross { get; set; }
        public decimal GrossAdj { get; set; }
        public decimal GST { get; set; }
        public decimal GSTAdj { get; set; }
        public decimal AgencyComm { get; set; }
        public decimal AgencyCommAdj { get; set; }
        public decimal Receiable { get; set; }
        public decimal ReceiableAdj { get; set; }
        public decimal OtherCharges { get; set; }
        public decimal OtherChargesAdj { get; set; }
        public string Reason { get; set; }
        public int AdjustmentStatusId { get; set; }
        public bool IsLumpSum { get; set; }
        public decimal LumpSumDiscount { get; set; }
        public decimal LumpSumPremium { get; set; }
        public bool IsGSTLoad { get; set; }
        public string AgainstCrDr { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<int> ChannelID { get; set; }
        public Nullable<int> ComnpanyID { get; set; }
        public System.DateTime AdjustmentDate { get; set; }
    
        public virtual AdjustmentStatu AdjustmentStatu { get; set; }
        public virtual Agency Agency { get; set; }
        public virtual Channel Channel { get; set; }
        public virtual InvoiceMaster InvoiceMaster { get; set; }
        public virtual Portal Portal { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AdjustmentDetail> AdjustmentDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CRVCN__> CRVCN__ { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InvDN> InvDNs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LedgerBalance> LedgerBalances { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LSAdjustmentDetail> LSAdjustmentDetails { get; set; }
    }
}
