//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExpressDigital
{
    using System;
    using System.Collections.Generic;
    
    public partial class Client
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Client()
        {
            this.ReleaseOrderMasters = new HashSet<ReleaseOrderMaster>();
        }
    
        public int ID { get; set; }
        public string Client1 { get; set; }
        public Nullable<int> AgencyID { get; set; }
        public string ContactPerson { get; set; }
        public string GSTNo { get; set; }
        public string NICNo { get; set; }
        public string NTNNo { get; set; }
        public string Address { get; set; }
        public Nullable<int> CountryID { get; set; }
        public Nullable<int> StateID { get; set; }
        public Nullable<int> CityID { get; set; }
        public string ContactNo { get; set; }
        public string Email { get; set; }
        public Nullable<bool> Suspended { get; set; }
        public Nullable<bool> Active { get; set; }
        public Nullable<bool> IsExempted { get; set; }
        public string UploadedFileName { get; set; }
        public byte[] UploadedFile { get; set; }
        public Nullable<decimal> GSTRation { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<int> ModifyBy { get; set; }
        public Nullable<System.DateTime> ModifyOn { get; set; }
        public Nullable<decimal> CreditLimit { get; set; }
        public Nullable<bool> IsGovernament { get; set; }
        public Nullable<int> GSTEffectiveStation { get; set; }
        public Nullable<bool> IsInternational { get; set; }
    
        public virtual Agency Agency { get; set; }
        public virtual CityManagement CityManagement { get; set; }
        public virtual Country Country { get; set; }
        public virtual CountryState CountryState { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ReleaseOrderMaster> ReleaseOrderMasters { get; set; }
    }
}
