//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExpressDigital
{
    using System;
    using System.Collections.Generic;
    
    public partial class Compain
    {
        public string ID { get; set; }
        public string CompaignName { get; set; }
        public int AgencyID { get; set; }
        public int ClientID { get; set; }
        public string Remarks { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public int CreatedBy { get; set; }
        public Nullable<int> ModifyBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
    }
}
