//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExpressDigital
{
    using System;
    using System.Collections.Generic;
    
    public partial class Company
    {
        public byte Company_Id { get; set; }
        public string GroupComp_Code { get; set; }
        public string Company_Name { get; set; }
        public string Abbreviation { get; set; }
        public string NTN { get; set; }
        public string Company_Code { get; set; }
        public string Rec_Added_By { get; set; }
        public Nullable<System.DateTime> Rec_Added_Date { get; set; }
        public Nullable<System.DateTime> Rec_Added_Time { get; set; }
        public string Rec_Edited_By { get; set; }
        public Nullable<System.DateTime> Rec_Edited_Date { get; set; }
        public Nullable<System.DateTime> Rec_Edited_Time { get; set; }
        public string CREDITORS { get; set; }
        public string ADV_CREDITORS { get; set; }
        public Nullable<bool> Active { get; set; }
    }
}
