//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExpressDigital
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class DBScanEntities1 : DbContext
    {
        public DBScanEntities1()
            : base("name=DBScanEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<DigitalDocument> DigitalDocuments { get; set; }
    
        public virtual ObjectResult<usp_GetDigitalScanDocument_Result> usp_GetDigitalScanDocument(string iD, string type)
        {
            var iDParameter = iD != null ?
                new ObjectParameter("ID", iD) :
                new ObjectParameter("ID", typeof(string));
    
            var typeParameter = type != null ?
                new ObjectParameter("Type", type) :
                new ObjectParameter("Type", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_GetDigitalScanDocument_Result>("usp_GetDigitalScanDocument", iDParameter, typeParameter);
        }
    
        public virtual ObjectResult<usp_GetDigitalScanDocumentByID_Result> usp_GetDigitalScanDocumentByID(Nullable<int> iD)
        {
            var iDParameter = iD.HasValue ?
                new ObjectParameter("ID", iD) :
                new ObjectParameter("ID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_GetDigitalScanDocumentByID_Result>("usp_GetDigitalScanDocumentByID", iDParameter);
        }
    }
}
