//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExpressDigital
{
    using System;
    using System.Collections.Generic;
    
    public partial class GLAccounttHead
    {
        public string AccountTitle { get; set; }
        public string AccountHead { get; set; }
        public Nullable<int> CompanyID { get; set; }
        public string Acc_category { get; set; }
    }
}
