//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExpressDigital
{
    using System;
    using System.Collections.Generic;
    
    public partial class GroupAgency
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public GroupAgency()
        {
            this.Agencies = new HashSet<Agency>();
            this.SuspentionRestorationOptions = new HashSet<SuspentionRestorationOption>();
        }
    
        public int ID { get; set; }
        public string GroupName { get; set; }
        public string OwenrName { get; set; }
        public string GSTNumber { get; set; }
        public string PhoneNumber { get; set; }
        public string CellNumber { get; set; }
        public string FaxNumber { get; set; }
        public string Email { get; set; }
        public string Address { get; set; }
        public Nullable<int> CityID { get; set; }
        public Nullable<bool> Active { get; set; }
        public Nullable<bool> Commission { get; set; }
        public Nullable<decimal> CommPercentage { get; set; }
        public Nullable<int> CurrencyModeID { get; set; }
        public string AgecnyClient { get; set; }
        public string Remarks { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifyOn { get; set; }
        public Nullable<int> ModifyBy { get; set; }
        public Nullable<bool> Suspended { get; set; }
        public string AgencyStatus { get; set; }
        public Nullable<decimal> CreditLimit { get; set; }
        public string NTNNumber { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Agency> Agencies { get; set; }
        public virtual CityManagement CityManagement { get; set; }
        public virtual CurrencyMode CurrencyMode { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SuspentionRestorationOption> SuspentionRestorationOptions { get; set; }
    }
}
