//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExpressDigital
{
    using System;
    using System.Collections.Generic;
    
    public partial class InvDN
    {
        public int ID { get; set; }
        public string DNNo { get; set; }
        public int InvoiceId { get; set; }
        public string InvoiceNo { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreationDate { get; set; }
        public decimal TotalAmount { get; set; }
        public decimal PaidAmount { get; set; }
        public decimal RemainingAmount { get; set; }
        public bool IsBilled { get; set; }
        public int AdjustmentId { get; set; }
    
        public virtual Adjustment Adjustment { get; set; }
        public virtual InvoiceMaster InvoiceMaster { get; set; }
    }
}
