//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExpressDigital
{
    using System;
    using System.Collections.Generic;
    
    public partial class InvoiceDocumentDetail
    {
        public int ID { get; set; }
        public int DocumentId { get; set; }
        public int InvoiceId { get; set; }
        public string InvoiceNo { get; set; }
        public System.DateTime InvoiceDate { get; set; }
        public string RO_ReferenceNo { get; set; }
        public System.DateTime RO_Date { get; set; }
    
        public virtual InvoiceDocument InvoiceDocument { get; set; }
        public virtual InvoiceMaster InvoiceMaster { get; set; }
    }
}
