//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExpressDigital
{
    using System;
    using System.Collections.Generic;
    
    public partial class InvoiceDocument
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public InvoiceDocument()
        {
            this.InvoiceDocumentDetails = new HashSet<InvoiceDocumentDetail>();
        }
    
        public int ID { get; set; }
        public string ReferenceNumber { get; set; }
        public System.DateTime CreationDate { get; set; }
        public int AgencyID { get; set; }
        public int ClientId { get; set; }
        public string Status { get; set; }
        public string PersonName { get; set; }
        public string Description { get; set; }
    
        public virtual Agency Agency { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InvoiceDocumentDetail> InvoiceDocumentDetails { get; set; }
    }
}
