//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExpressDigital
{
    using System;
    using System.Collections.Generic;
    
    public partial class PaymentDetail
    {
        public int ID { get; set; }
        public int PaymentId { get; set; }
        public int ClientId { get; set; }
        public int InvoiceId { get; set; }
        public decimal AmountPaid { get; set; }
        public Nullable<bool> IsDN { get; set; }
    
        public virtual InvoiceMaster InvoiceMaster { get; set; }
        public virtual Payment Payment { get; set; }
    }
}
