//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExpressDigital
{
    using System;
    using System.Collections.Generic;
    
    public partial class Publication
    {
        public string Id { get; set; }
        public string Publication_Name { get; set; }
        public string Pub_Abreviation { get; set; }
        public bool In_House_Publication { get; set; }
        public string Rec_Added_By { get; set; }
        public Nullable<System.DateTime> Rec_Added_Date { get; set; }
        public Nullable<System.DateTime> Rec_Added_Time { get; set; }
        public string Rec_Edited_By { get; set; }
        public Nullable<System.DateTime> Rec_Edited_Date { get; set; }
        public Nullable<System.DateTime> Rec_Edited_Time { get; set; }
        public System.Guid rowguid { get; set; }
    }
}
