//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExpressDigital
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReleaseOrderDetail
    {
        public int ID { get; set; }
        public int ReleaseOrderID { get; set; }
        public Nullable<int> RegionID { get; set; }
        public int PortalID { get; set; }
        public Nullable<int> BannerID { get; set; }
        public int CurrencyID { get; set; }
        public Nullable<decimal> CurrencyValue { get; set; }
        public Nullable<decimal> ConversionRate { get; set; }
        public string CPMRate { get; set; }
        public System.DateTime StartDate { get; set; }
        public System.DateTime EndDate { get; set; }
        public int Weight { get; set; }
        public string Impressions { get; set; }
        public decimal TotalBilled { get; set; }
        public decimal Discount { get; set; }
        public decimal NetAmount { get; set; }
        public decimal NetReceiable { get; set; }
        public decimal GSTPercentage { get; set; }
        public decimal GSTAmount { get; set; }
        public decimal AGCPercentage { get; set; }
        public decimal AGCommission { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public string Remarks { get; set; }
        public string DeleiveredExpresssions { get; set; }
    
        public virtual Portal Portal { get; set; }
        public virtual ReleaseOrderMaster ReleaseOrderMaster { get; set; }
    }
}
