//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExpressDigital
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReleaseOrderSTI
    {
        public int ID { get; set; }
        public string RORefNo { get; set; }
        public System.DateTime RODate { get; set; }
        public bool IsCanceled { get; set; }
    }
}
