//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExpressDigital
{
    using System;
    using System.Collections.Generic;
    
    public partial class SettlementPlanDetail
    {
        public int ID { get; set; }
        public int SettlementPlanId { get; set; }
        public Nullable<int> ClientId { get; set; }
        public int InvoiceId { get; set; }
        public decimal AmountPaid { get; set; }
        public Nullable<bool> IsDN { get; set; }
        public System.DateTime CreationDate { get; set; }
        public int CreatedBy { get; set; }
        public Nullable<int> ActiveId { get; set; }
        public Nullable<System.DateTime> ModificationDate { get; set; }
        public Nullable<int> ModificationBy { get; set; }
        public int PortalID { get; set; }
        public bool Posted { get; set; }
    
        public virtual SettlementPlan SettlementPlan { get; set; }
    }
}
