//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExpressDigital
{
    using System;
    using System.Collections.Generic;
    
    public partial class SettlementPlan
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SettlementPlan()
        {
            this.SettlementPlanDetails = new HashSet<SettlementPlanDetail>();
        }
    
        public int ID { get; set; }
        public int CRVId { get; set; }
        public int AgencyId { get; set; }
        public System.DateTime PaymentDate { get; set; }
        public string PaymentMode { get; set; }
        public Nullable<bool> IsCN { get; set; }
        public Nullable<int> CRVDetail_CRVCN_ClientId { get; set; }
        public Nullable<int> CompanyID { get; set; }
        public Nullable<int> ChannelID { get; set; }
    
        public virtual Agency Agency { get; set; }
        public virtual tblCRV tblCRV { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SettlementPlanDetail> SettlementPlanDetails { get; set; }
    }
}
