//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExpressDigital
{
    using System;
    using System.Collections.Generic;
    
    public partial class SuspentionRestorationAgencyOption
    {
        public int ID { get; set; }
        public int AgencyID { get; set; }
        public string Agency_Client { get; set; }
        public string Remarks { get; set; }
        public int ActionBy { get; set; }
        public System.DateTime ActionOn { get; set; }
        public bool SystemResotre { get; set; }
        public byte[] RefLetter { get; set; }
        public System.DateTime SusResDate { get; set; }
        public string UoloadedFileName { get; set; }
    
        public virtual Agency Agency { get; set; }
        public virtual UserInfo UserInfo { get; set; }
    }
}
