//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExpressDigital
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblDocument
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblDocument()
        {
            this.tblDocumentDetails = new HashSet<tblDocumentDetail>();
        }
    
        public int DocumentID { get; set; }
        public string ReferenceNumber { get; set; }
        public System.DateTime CreationDate { get; set; }
        public int AgencyID { get; set; }
        public string Status { get; set; }
        public Nullable<System.DateTime> DeliveryDate { get; set; }
        public string PersonName { get; set; }
    
        public virtual Agency Agency { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblDocumentDetail> tblDocumentDetails { get; set; }
    }
}
