//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExpressDigital
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblSettlementPlanDetail___
    {
        public int ID { get; set; }
        public Nullable<int> SettlementPlanId { get; set; }
        public Nullable<int> ClientId { get; set; }
        public Nullable<int> InvoiceId { get; set; }
        public Nullable<decimal> AmountPaid { get; set; }
        public Nullable<bool> IsDN { get; set; }
        public Nullable<System.DateTime> CreationDate { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<int> ActiveId { get; set; }
        public Nullable<System.DateTime> ModificationDate { get; set; }
        public Nullable<int> ModificationBy { get; set; }
    }
}
