//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExpressDigital
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserInfo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public UserInfo()
        {
            this.ReleaseOrderMasters = new HashSet<ReleaseOrderMaster>();
            this.ReleaseOrderMasters1 = new HashSet<ReleaseOrderMaster>();
            this.SuspentionRestorationAgencyOptions = new HashSet<SuspentionRestorationAgencyOption>();
            this.SuspentionRestorationOptions = new HashSet<SuspentionRestorationOption>();
        }
    
        public int ID { get; set; }
        public string UserName { get; set; }
        public string UserID { get; set; }
        public string UserPassword { get; set; }
        public int RoleID { get; set; }
        public string Email { get; set; }
        public string Contact { get; set; }
        public bool IsActive { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public int CreatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ReleaseOrderMaster> ReleaseOrderMasters { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ReleaseOrderMaster> ReleaseOrderMasters1 { get; set; }
        public virtual Role Role { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SuspentionRestorationAgencyOption> SuspentionRestorationAgencyOptions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SuspentionRestorationOption> SuspentionRestorationOptions { get; set; }
    }
}
