//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExpressDigital
{
    using System;
    using System.Collections.Generic;
    
    public partial class VInvoicePrintData
    {
        public int invoiceID { get; set; }
        public Nullable<int> ReleaseOrderID { get; set; }
        public decimal GrossAmount { get; set; }
        public decimal NetReceiable { get; set; }
        public decimal RecivedAmount { get; set; }
        public decimal BalanceAmount { get; set; }
        public int PaymentStatusID { get; set; }
        public int ClientID { get; set; }
        public int AgencyID { get; set; }
        public bool IsCancelled { get; set; }
        public Nullable<int> CancelledBy { get; set; }
        public Nullable<System.DateTime> CancelledOn { get; set; }
        public short dollarinvoice { get; set; }
        public System.DateTime FromDate { get; set; }
        public System.DateTime ToDate { get; set; }
        public Nullable<decimal> GSTAmount { get; set; }
        public Nullable<decimal> AGCAmount { get; set; }
        public Nullable<decimal> NetAmount { get; set; }
        public Nullable<decimal> InvoiceGross { get; set; }
        public Nullable<decimal> InvoiceDiscount { get; set; }
        public string PortalName { get; set; }
        public string Client { get; set; }
        public string GSTNo { get; set; }
        public string NICNo { get; set; }
        public string NTNNo { get; set; }
        public string clientAddress { get; set; }
        public Nullable<int> ClientCountyID { get; set; }
        public Nullable<int> StateID { get; set; }
        public Nullable<int> ClientCityID { get; set; }
        public string ClientContact { get; set; }
        public string ClientEmail { get; set; }
        public Nullable<bool> IsExempted { get; set; }
        public string AgencyName { get; set; }
        public string PhoneNumber { get; set; }
        public string CellNumber { get; set; }
        public string AgencyFaxnumber { get; set; }
        public string AgencyEmail { get; set; }
        public string AgencyAddress { get; set; }
        public string AgencyClinet { get; set; }
        public int AgencyCityID { get; set; }
        public decimal GSTPercentage { get; set; }
        public string GSTNumber { get; set; }
        public Nullable<decimal> CommPercentage { get; set; }
        public string NTNNumber { get; set; }
        public string Compaign { get; set; }
        public string Remarks { get; set; }
        public int CreatedBy { get; set; }
        public string InviceDate { get; set; }
        public string ReleaseOrderNumber { get; set; }
        public string FOCPAID { get; set; }
        public string ROExternal { get; set; }
        public string ROMPDate { get; set; }
        public string CamStartDate { get; set; }
        public string CamEndDate { get; set; }
        public string ReleaseOrderReferenceID { get; set; }
        public int ReleaseOrderDetailId { get; set; }
        public int CurrencyID { get; set; }
        public Nullable<decimal> CurrencyValue { get; set; }
        public Nullable<decimal> ConversionRate { get; set; }
        public string CPMRate { get; set; }
        public decimal Discount { get; set; }
        public decimal D_NetAmount { get; set; }
        public decimal d_NetReceiable { get; set; }
        public decimal d_GSTPercentage { get; set; }
        public Nullable<int> CompanyID { get; set; }
        public decimal d_GSTAmount { get; set; }
        public decimal AGCPercentage { get; set; }
        public decimal AGCommission { get; set; }
        public int d_CreatedBy { get; set; }
        public decimal TotalBilled { get; set; }
        public string Impressions { get; set; }
        public int IsBilled { get; set; }
        public Nullable<System.DateTime> ReleaseOrderDate { get; set; }
    }
}
