//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExpressDigital
{
    using System;
    using System.Collections.Generic;
    
    public partial class vUpdateExpressionList
    {
        public int ID { get; set; }
        public string ReleaseOrderSequenceID { get; set; }
        public string ReleaseOrderReferenceID { get; set; }
        public string ROMPDate { get; set; }
        public string AgencyName { get; set; }
        public string Client { get; set; }
        public string CompaignName { get; set; }
        public int Impressions { get; set; }
        public int DeliveredImpressions { get; set; }
        public System.DateTime StartDate { get; set; }
        public System.DateTime EndDate { get; set; }
        public decimal RateCPM { get; set; }
        public decimal DiscountOffered { get; set; }
        public decimal ConversionRate { get; set; }
        public string FOCPAID { get; set; }
        public decimal GSTRate { get; set; }
        public decimal AGCommission { get; set; }
        public string AGStatus { get; set; }
    }
}
