//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AMR
{
    using System;
    using System.Collections.Generic;
    
    public partial class AgencyExecutive
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AgencyExecutive()
        {
            this.AgencyExecChecks = new HashSet<AgencyExecCheck>();
        }
    
        public int Id { get; set; }
        public string Status { get; set; }
        public Nullable<int> Agency_Id { get; set; }
        public string Executive_Name { get; set; }
        public string Designation { get; set; }
        public string Direct_Phone { get; set; }
        public string Mobile_Phone { get; set; }
        public string EMail_Address { get; set; }
        public string Remarks { get; set; }
        public string Address { get; set; }
        public string Phone { get; set; }
        public string City { get; set; }
        public Nullable<int> Postal_Code { get; set; }
        public string Department { get; set; }
        public Nullable<System.DateTime> DOB { get; set; }
        public string Marital_Status { get; set; }
        public Nullable<System.DateTime> Wedding_Ann { get; set; }
        public string Exec1_Id { get; set; }
        public string Exec1_Rel { get; set; }
        public string Exec1_Remarks { get; set; }
        public string Exec2_Id { get; set; }
        public string Exec2_Rel { get; set; }
        public string Exec2_Remarks { get; set; }
        public string Rec_Added_By { get; set; }
        public Nullable<System.DateTime> Rec_Added_Date { get; set; }
        public Nullable<System.DateTime> Rec_Added_Time { get; set; }
        public string Rec_Edited_By { get; set; }
        public Nullable<System.DateTime> Rec_Edited_Date { get; set; }
        public Nullable<System.DateTime> Rec_Edited_Time { get; set; }
        public Nullable<byte> Grp { get; set; }
        public bool cExport { get; set; }
        public Nullable<int> Gen_Remarks { get; set; }
    
        public virtual Agency Agency { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AgencyExecCheck> AgencyExecChecks { get; set; }
    }
}
