//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AMR
{
    using System;
    using System.Collections.Generic;
    
    public partial class BrandCampaign_unused
    {
        public int Id { get; set; }
        public Nullable<int> CR_Id { get; set; }
        public Nullable<int> Brand_Id { get; set; }
        public string Campaign_Title { get; set; }
        public Nullable<System.DateTime> Expected_Launch_Date { get; set; }
        public bool During_The_Month { get; set; }
        public Nullable<int> Expected_Budget { get; set; }
        public bool Edition_ISB { get; set; }
        public bool Edition_KHI { get; set; }
        public bool Edition_LHE { get; set; }
        public bool Edition_PEW { get; set; }
        public bool Edition_QTA { get; set; }
        public bool Edition_MUX { get; set; }
        public bool Edition_FSB { get; set; }
        public bool Edition_GUJ { get; set; }
        public bool Edition_SGD { get; set; }
        public string Rec_Added_By { get; set; }
        public Nullable<System.DateTime> Rec_Added_Date { get; set; }
        public Nullable<System.DateTime> Rec_Added_Time { get; set; }
        public string Rec_Edited_By { get; set; }
        public Nullable<System.DateTime> Rec_Edited_Date { get; set; }
        public Nullable<System.DateTime> Rec_Edited_Time { get; set; }
        public Nullable<byte> Grp { get; set; }
        public System.Guid rowguid { get; set; }
    }
}
