//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AMR
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClientSector
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public string Remarks { get; set; }
        public string Rec_Added_By { get; set; }
        public Nullable<System.DateTime> Rec_Added_Date { get; set; }
        public Nullable<System.DateTime> Rec_Added_Time { get; set; }
        public string Rec_Edited_By { get; set; }
        public Nullable<System.DateTime> Rec_Edited_Date { get; set; }
        public Nullable<System.DateTime> Rec_Edited_Time { get; set; }
    }
}
