//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AMR
{
    using System;
    using System.Collections.Generic;
    
    public partial class ContactReport
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ContactReport()
        {
            this.ContactReportChks = new HashSet<ContactReportChk>();
        }
    
        public int Id { get; set; }
        public string Rec_Type { get; set; }
        public string Visit_To { get; set; }
        public Nullable<int> Main_Category { get; set; }
        public Nullable<int> Sub_Category { get; set; }
        public Nullable<int> Agency_Client_Id { get; set; }
        public Nullable<int> Brand_Id { get; set; }
        public Nullable<System.DateTime> Visit_Date { get; set; }
        public string Minutes_Of_Meeting { get; set; }
        public bool PR_Visit { get; set; }
        public Nullable<bool> New_Executive { get; set; }
        public string Follow_Up_Mode { get; set; }
        public Nullable<System.DateTime> Follow_Up_Date { get; set; }
        public string Follow_Up_Time { get; set; }
        public string Follow_Up_Visit_Mode { get; set; }
        public Nullable<int> Follow_Up_Visit_To { get; set; }
        public string Ad_Confirm { get; set; }
        public Nullable<int> Cm { get; set; }
        public Nullable<byte> Col { get; set; }
        public string Color { get; set; }
        public string Remarks { get; set; }
        public Nullable<int> CPR_Activity { get; set; }
        public Nullable<int> CPR_Qty_Amount { get; set; }
        public Nullable<System.DateTime> Confirm_Date { get; set; }
        public Nullable<int> Confirm_Publication { get; set; }
        public Nullable<byte> Confirm_Page { get; set; }
        public bool Confirm_Edition_ISB { get; set; }
        public bool Confirm_Edition_KHI { get; set; }
        public bool Confirm_Edition_LHE { get; set; }
        public bool Confirm_Edition_PEW { get; set; }
        public bool Confirm_Edition_QTA { get; set; }
        public bool Confirm_Edition_MUX { get; set; }
        public bool Confirm_Edition_FSB { get; set; }
        public bool Confirm_Edition_GUJ { get; set; }
        public bool Confirm_Edition_SGD { get; set; }
        public string Reason_Of_Refusal { get; set; }
        public bool Any_New_Campaign { get; set; }
        public string Campaign_Title { get; set; }
        public Nullable<System.DateTime> Expected_Launch { get; set; }
        public bool Or_During_The_Month { get; set; }
        public Nullable<int> Expected_Budget { get; set; }
        public bool Expected_Edition_ISB { get; set; }
        public bool Expected_Edition_KHI { get; set; }
        public bool Expected_Edition_LHE { get; set; }
        public bool Expected_Edition_PEW { get; set; }
        public bool Expected_Edition_QTA { get; set; }
        public bool Expected_Edition_MUX { get; set; }
        public bool Expected_Edition_FSB { get; set; }
        public bool Expected_Edition_GRW { get; set; }
        public bool Expected_Edition_SGD { get; set; }
        public bool Issues { get; set; }
        public string Issues_Remarks { get; set; }
        public string Rec_Added_By { get; set; }
        public Nullable<System.DateTime> Rec_Added_Date { get; set; }
        public Nullable<System.DateTime> Rec_Added_Time { get; set; }
        public string Rec_Edited_By { get; set; }
        public Nullable<System.DateTime> Rec_Edited_Date { get; set; }
        public Nullable<System.DateTime> Rec_Edited_Time { get; set; }
        public Nullable<byte> Grp { get; set; }
        public bool cExport { get; set; }
        public Nullable<int> Gen_Minutes_Of_Meeting { get; set; }
        public Nullable<int> Gen_Reason_Of_Refusal { get; set; }
        public System.Guid rowguid { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ContactReportChk> ContactReportChks { get; set; }
    }
}
