//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AMR
{
    using System;
    using System.Collections.Generic;
    
    public partial class DynamicTable
    {
        public Nullable<System.DateTime> Publication_Date { get; set; }
        public int Client_Id { get; set; }
        public string Client_Name { get; set; }
        public Nullable<int> Group_Id { get; set; }
        public string group_name { get; set; }
        public Nullable<int> Publication { get; set; }
        public string Pub_Abreviation { get; set; }
        public Nullable<int> Type_Id { get; set; }
        public string Type { get; set; }
        public Nullable<int> FSB { get; set; }
        public Nullable<int> GUJ { get; set; }
        public Nullable<int> HYD { get; set; }
        public Nullable<int> ISB { get; set; }
        public Nullable<int> KHI { get; set; }
        public Nullable<int> LHE { get; set; }
        public Nullable<int> MUX { get; set; }
        public Nullable<int> PEW { get; set; }
        public Nullable<int> QTA { get; set; }
        public Nullable<int> RYK { get; set; }
        public Nullable<int> SGD { get; set; }
        public Nullable<int> SUK { get; set; }
        public Nullable<int> Total { get; set; }
    }
}
