//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AMR
{
    using System;
    using System.Collections.Generic;
    
    public partial class MainRate
    {
        public int RecId { get; set; }
        public int MainCat_Id { get; set; }
        public int Publication_id { get; set; }
        public int Edition_Id { get; set; }
        public int Rate { get; set; }
    
        public virtual GroupComp GroupComp { get; set; }
        public virtual MainCategory MainCategory { get; set; }
        public virtual Publication Publication { get; set; }
    }
}
