//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AMR
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class Model1Container : DbContext
    {
        public Model1Container()
            : base("name=Model1Container")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ActivityLog> ActivityLogs { get; set; }
        public virtual DbSet<AExecutiveBrand> AExecutiveBrands { get; set; }
        public virtual DbSet<Agency> Agencies { get; set; }
        public virtual DbSet<AgencyAssignments_unused> AgencyAssignments_unused { get; set; }
        public virtual DbSet<AgencyBrand> AgencyBrands { get; set; }
        public virtual DbSet<AgencyExecutive> AgencyExecutives { get; set; }
        public virtual DbSet<Branch> Branches { get; set; }
        public virtual DbSet<BrandCampaign_unused> BrandCampaign_unused { get; set; }
        public virtual DbSet<Brand> Brands { get; set; }
        public virtual DbSet<Campaign> Campaigns { get; set; }
        public virtual DbSet<CExecutiveBrand> CExecutiveBrands { get; set; }
        public virtual DbSet<CExecutiveBrands_unused> CExecutiveBrands_unused { get; set; }
        public virtual DbSet<ClientCompany> ClientCompanies { get; set; }
        public virtual DbSet<ClientExecutive> ClientExecutives { get; set; }
        public virtual DbSet<ClientSector> ClientSectors { get; set; }
        public virtual DbSet<ClubCategory> ClubCategories { get; set; }
        public virtual DbSet<Company> Companies { get; set; }
        public virtual DbSet<CompGRelation> CompGRelations { get; set; }
        public virtual DbSet<CompGroup> CompGroups { get; set; }
        public virtual DbSet<CompGStation> CompGStations { get; set; }
        public virtual DbSet<ContactReport> ContactReports { get; set; }
        public virtual DbSet<contactreport_mobile> contactreport_mobile { get; set; }
        public virtual DbSet<Contactreportmobile_Detail> Contactreportmobile_Detail { get; set; }
        public virtual DbSet<CPRActivity> CPRActivities { get; set; }
        public virtual DbSet<CRUsers_unused> CRUsers_unused { get; set; }
        public virtual DbSet<DailyRevenue> DailyRevenues { get; set; }
        public virtual DbSet<Department> Departments { get; set; }
        public virtual DbSet<Designation> Designations { get; set; }
        public virtual DbSet<Division> Divisions { get; set; }
        public virtual DbSet<dtproperty> dtproperties { get; set; }
        public virtual DbSet<ExportTable_unused> ExportTable_unused { get; set; }
        public virtual DbSet<FollowUpExecutive> FollowUpExecutives { get; set; }
        public virtual DbSet<GroupComp> GroupComps { get; set; }
        public virtual DbSet<GroupSecurity> GroupSecurities { get; set; }
        public virtual DbSet<Help> Helps { get; set; }
        public virtual DbSet<IdCtr> IdCtrs { get; set; }
        public virtual DbSet<LogManager> LogManagers { get; set; }
        public virtual DbSet<LogRecord> LogRecords { get; set; }
        public virtual DbSet<MainCategory> MainCategories { get; set; }
        public virtual DbSet<MainRate> MainRates { get; set; }
        public virtual DbSet<MediaBuyingHouses_unused> MediaBuyingHouses_unused { get; set; }
        public virtual DbSet<MeetingExecutive> MeetingExecutives { get; set; }
        public virtual DbSet<MenuItem> MenuItems { get; set; }
        public virtual DbSet<Menu> Menus { get; set; }
        public virtual DbSet<MonthlyTarget> MonthlyTargets { get; set; }
        public virtual DbSet<Organisation> Organisations { get; set; }
        public virtual DbSet<OrganizationChartBI> OrganizationChartBIs { get; set; }
        public virtual DbSet<OrgSecurity> OrgSecurities { get; set; }
        public virtual DbSet<PublicationGroupDetail> PublicationGroupDetails { get; set; }
        public virtual DbSet<PublicationGroup> PublicationGroups { get; set; }
        public virtual DbSet<Publication> Publications { get; set; }
        public virtual DbSet<RateCard> RateCards { get; set; }
        public virtual DbSet<RatePolicy> RatePolicies { get; set; }
        public virtual DbSet<RatePolicyStation> RatePolicyStations { get; set; }
        public virtual DbSet<Role> Roles { get; set; }
        public virtual DbSet<RolesItem> RolesItems { get; set; }
        public virtual DbSet<RolesItem_new> RolesItem_new { get; set; }
        public virtual DbSet<SecurityControl> SecurityControls { get; set; }
        public virtual DbSet<SubBranch> SubBranches { get; set; }
        public virtual DbSet<SubCategory> SubCategories { get; set; }
        public virtual DbSet<SubRate> SubRates { get; set; }
        public virtual DbSet<TemplateMinute> TemplateMinutes { get; set; }
        public virtual DbSet<Track_IDs_unused> Track_IDs_unused { get; set; }
        public virtual DbSet<TransactionAdd> TransactionAdds { get; set; }
        public virtual DbSet<Transaction> Transactions { get; set; }
        public virtual DbSet<Type> Types { get; set; }
        public virtual DbSet<UserGroup> UserGroups { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<UserSecurity> UserSecurities { get; set; }
        public virtual DbSet<AgeBraCli> AgeBraClis { get; set; }
        public virtual DbSet<AgencyClient_Com> AgencyClient_Com { get; set; }
        public virtual DbSet<AgencyExecCheck> AgencyExecChecks { get; set; }
        public virtual DbSet<AgencyGroup> AgencyGroups { get; set; }
        public virtual DbSet<AgencyGroupDtl> AgencyGroupDtls { get; set; }
        public virtual DbSet<CaterogiesClient> CaterogiesClients { get; set; }
        public virtual DbSet<ClientExecutiveCheck> ClientExecutiveChecks { get; set; }
        public virtual DbSet<ContactReportChk> ContactReportChks { get; set; }
        public virtual DbSet<CRUser> CRUsers { get; set; }
        public virtual DbSet<DailyRevenueChk> DailyRevenueChks { get; set; }
        public virtual DbSet<DummyTable> DummyTables { get; set; }
        public virtual DbSet<DynamicTable> DynamicTables { get; set; }
        public virtual DbSet<Missing> Missings { get; set; }
        public virtual DbSet<MissingExective> MissingExectives { get; set; }
        public virtual DbSet<MissingParameter> MissingParameters { get; set; }
        public virtual DbSet<MissingRight> MissingRights { get; set; }
        public virtual DbSet<MonthlyTartgetCheck> MonthlyTartgetChecks { get; set; }
        public virtual DbSet<RateCardBaseStation> RateCardBaseStations { get; set; }
        public virtual DbSet<Relation_Execs> Relation_Execs { get; set; }
        public virtual DbSet<Relations_Execs> Relations_Execs { get; set; }
        public virtual DbSet<Software> Softwares { get; set; }
        public virtual DbSet<temp_desg> temp_desg { get; set; }
        public virtual DbSet<TempAddM_Visit_1> TempAddM_Visit_1 { get; set; }
        public virtual DbSet<TempAddMiss_1> TempAddMiss_1 { get; set; }
        public virtual DbSet<TempClientCompany> TempClientCompanies { get; set; }
        public virtual DbSet<tempID> tempIDs { get; set; }
        public virtual DbSet<TempVolumeTrend> TempVolumeTrends { get; set; }
        public virtual DbSet<Transaction_Dup> Transaction_Dup { get; set; }
        public virtual DbSet<TransactionChk> TransactionChks { get; set; }
        public virtual DbSet<RateCardDetail> RateCardDetails { get; set; }
    
        public virtual ObjectResult<Nullable<int>> usp_IDctr(string for_Table)
        {
            var for_TableParameter = for_Table != null ?
                new ObjectParameter("For_Table", for_Table) :
                new ObjectParameter("For_Table", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("usp_IDctr", for_TableParameter);
        }
    
        public virtual int GettransactionDatafor_report(Nullable<int> groupId, Nullable<System.DateTime> startDate, Nullable<System.DateTime> endDate)
        {
            var groupIdParameter = groupId.HasValue ?
                new ObjectParameter("GroupId", groupId) :
                new ObjectParameter("GroupId", typeof(int));
    
            var startDateParameter = startDate.HasValue ?
                new ObjectParameter("StartDate", startDate) :
                new ObjectParameter("StartDate", typeof(System.DateTime));
    
            var endDateParameter = endDate.HasValue ?
                new ObjectParameter("EndDate", endDate) :
                new ObjectParameter("EndDate", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("GettransactionDatafor_report", groupIdParameter, startDateParameter, endDateParameter);
        }
    
        [DbFunction("Model1Container", "SplitString")]
        public virtual IQueryable<Nullable<int>> SplitString(string inputString, string delimiter)
        {
            var inputStringParameter = inputString != null ?
                new ObjectParameter("InputString", inputString) :
                new ObjectParameter("InputString", typeof(string));
    
            var delimiterParameter = delimiter != null ?
                new ObjectParameter("Delimiter", delimiter) :
                new ObjectParameter("Delimiter", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<Nullable<int>>("[Model1Container].[SplitString](@InputString, @Delimiter)", inputStringParameter, delimiterParameter);
        }
    
        [DbFunction("Model1Container", "GetRateCardSummary")]
        public virtual IQueryable<Nullable<decimal>> GetRateCardSummary(Nullable<int> publication, Nullable<int> main_Category, Nullable<System.DateTime> publication_Date, string city_Editions)
        {
            var publicationParameter = publication.HasValue ?
                new ObjectParameter("Publication", publication) :
                new ObjectParameter("Publication", typeof(int));
    
            var main_CategoryParameter = main_Category.HasValue ?
                new ObjectParameter("Main_Category", main_Category) :
                new ObjectParameter("Main_Category", typeof(int));
    
            var publication_DateParameter = publication_Date.HasValue ?
                new ObjectParameter("Publication_Date", publication_Date) :
                new ObjectParameter("Publication_Date", typeof(System.DateTime));
    
            var city_EditionsParameter = city_Editions != null ?
                new ObjectParameter("City_Editions", city_Editions) :
                new ObjectParameter("City_Editions", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<Nullable<decimal>>("[Model1Container].[GetRateCardSummary](@Publication, @Main_Category, @Publication_Date, @City_Editions)", publicationParameter, main_CategoryParameter, publication_DateParameter, city_EditionsParameter);
        }
    
        public virtual int Revenue_report(Nullable<System.DateTime> startDate, Nullable<System.DateTime> endDate, Nullable<int> publication, Nullable<int> mainCategory)
        {
            var startDateParameter = startDate.HasValue ?
                new ObjectParameter("StartDate", startDate) :
                new ObjectParameter("StartDate", typeof(System.DateTime));
    
            var endDateParameter = endDate.HasValue ?
                new ObjectParameter("EndDate", endDate) :
                new ObjectParameter("EndDate", typeof(System.DateTime));
    
            var publicationParameter = publication.HasValue ?
                new ObjectParameter("Publication", publication) :
                new ObjectParameter("Publication", typeof(int));
    
            var mainCategoryParameter = mainCategory.HasValue ?
                new ObjectParameter("MainCategory", mainCategory) :
                new ObjectParameter("MainCategory", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Revenue_report", startDateParameter, endDateParameter, publicationParameter, mainCategoryParameter);
        }
    
        [DbFunction("Model1Container", "SplitString_string")]
        public virtual IQueryable<string> SplitString_string(string inputString, string delimiter)
        {
            var inputStringParameter = inputString != null ?
                new ObjectParameter("InputString", inputString) :
                new ObjectParameter("InputString", typeof(string));
    
            var delimiterParameter = delimiter != null ?
                new ObjectParameter("Delimiter", delimiter) :
                new ObjectParameter("Delimiter", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<string>("[Model1Container].[SplitString_string](@InputString, @Delimiter)", inputStringParameter, delimiterParameter);
        }
    
        public virtual int dashboard_report2(Nullable<int> groupId, Nullable<System.DateTime> startDate, Nullable<System.DateTime> endDate, Nullable<int> main_Category, string sub_Categories, string city_Editions)
        {
            var groupIdParameter = groupId.HasValue ?
                new ObjectParameter("GroupId", groupId) :
                new ObjectParameter("GroupId", typeof(int));
    
            var startDateParameter = startDate.HasValue ?
                new ObjectParameter("StartDate", startDate) :
                new ObjectParameter("StartDate", typeof(System.DateTime));
    
            var endDateParameter = endDate.HasValue ?
                new ObjectParameter("EndDate", endDate) :
                new ObjectParameter("EndDate", typeof(System.DateTime));
    
            var main_CategoryParameter = main_Category.HasValue ?
                new ObjectParameter("Main_Category", main_Category) :
                new ObjectParameter("Main_Category", typeof(int));
    
            var sub_CategoriesParameter = sub_Categories != null ?
                new ObjectParameter("Sub_Categories", sub_Categories) :
                new ObjectParameter("Sub_Categories", typeof(string));
    
            var city_EditionsParameter = city_Editions != null ?
                new ObjectParameter("City_Editions", city_Editions) :
                new ObjectParameter("City_Editions", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("dashboard_report2", groupIdParameter, startDateParameter, endDateParameter, main_CategoryParameter, sub_CategoriesParameter, city_EditionsParameter);
        }
    
        public virtual int dashboard_report3(Nullable<int> groupId, Nullable<System.DateTime> startDate, Nullable<System.DateTime> endDate, Nullable<int> main_Category, string sub_Categories, string city_Editions)
        {
            var groupIdParameter = groupId.HasValue ?
                new ObjectParameter("GroupId", groupId) :
                new ObjectParameter("GroupId", typeof(int));
    
            var startDateParameter = startDate.HasValue ?
                new ObjectParameter("StartDate", startDate) :
                new ObjectParameter("StartDate", typeof(System.DateTime));
    
            var endDateParameter = endDate.HasValue ?
                new ObjectParameter("EndDate", endDate) :
                new ObjectParameter("EndDate", typeof(System.DateTime));
    
            var main_CategoryParameter = main_Category.HasValue ?
                new ObjectParameter("Main_Category", main_Category) :
                new ObjectParameter("Main_Category", typeof(int));
    
            var sub_CategoriesParameter = sub_Categories != null ?
                new ObjectParameter("Sub_Categories", sub_Categories) :
                new ObjectParameter("Sub_Categories", typeof(string));
    
            var city_EditionsParameter = city_Editions != null ?
                new ObjectParameter("City_Editions", city_Editions) :
                new ObjectParameter("City_Editions", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("dashboard_report3", groupIdParameter, startDateParameter, endDateParameter, main_CategoryParameter, sub_CategoriesParameter, city_EditionsParameter);
        }
    
        public virtual int dashboard_report4(Nullable<int> groupId, Nullable<System.DateTime> startDate, Nullable<System.DateTime> endDate, Nullable<int> main_Category, string sub_Categories, string city_Editions)
        {
            var groupIdParameter = groupId.HasValue ?
                new ObjectParameter("GroupId", groupId) :
                new ObjectParameter("GroupId", typeof(int));
    
            var startDateParameter = startDate.HasValue ?
                new ObjectParameter("StartDate", startDate) :
                new ObjectParameter("StartDate", typeof(System.DateTime));
    
            var endDateParameter = endDate.HasValue ?
                new ObjectParameter("EndDate", endDate) :
                new ObjectParameter("EndDate", typeof(System.DateTime));
    
            var main_CategoryParameter = main_Category.HasValue ?
                new ObjectParameter("Main_Category", main_Category) :
                new ObjectParameter("Main_Category", typeof(int));
    
            var sub_CategoriesParameter = sub_Categories != null ?
                new ObjectParameter("Sub_Categories", sub_Categories) :
                new ObjectParameter("Sub_Categories", typeof(string));
    
            var city_EditionsParameter = city_Editions != null ?
                new ObjectParameter("City_Editions", city_Editions) :
                new ObjectParameter("City_Editions", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("dashboard_report4", groupIdParameter, startDateParameter, endDateParameter, main_CategoryParameter, sub_CategoriesParameter, city_EditionsParameter);
        }
    
        public virtual ObjectResult<dashboard_report_Express_Result> dashboard_report_Express(Nullable<int> groupId, Nullable<System.DateTime> startDate, Nullable<System.DateTime> endDate)
        {
            var groupIdParameter = groupId.HasValue ?
                new ObjectParameter("GroupId", groupId) :
                new ObjectParameter("GroupId", typeof(int));
    
            var startDateParameter = startDate.HasValue ?
                new ObjectParameter("StartDate", startDate) :
                new ObjectParameter("StartDate", typeof(System.DateTime));
    
            var endDateParameter = endDate.HasValue ?
                new ObjectParameter("EndDate", endDate) :
                new ObjectParameter("EndDate", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<dashboard_report_Express_Result>("dashboard_report_Express", groupIdParameter, startDateParameter, endDateParameter);
        }
    
        public virtual int dasboard_subcategory(Nullable<int> groupId, Nullable<System.DateTime> startDate, Nullable<System.DateTime> endDate)
        {
            var groupIdParameter = groupId.HasValue ?
                new ObjectParameter("GroupId", groupId) :
                new ObjectParameter("GroupId", typeof(int));
    
            var startDateParameter = startDate.HasValue ?
                new ObjectParameter("StartDate", startDate) :
                new ObjectParameter("StartDate", typeof(System.DateTime));
    
            var endDateParameter = endDate.HasValue ?
                new ObjectParameter("EndDate", endDate) :
                new ObjectParameter("EndDate", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("dasboard_subcategory", groupIdParameter, startDateParameter, endDateParameter);
        }
    
        public virtual int usp_GetTop10ClientPivotSummary(Nullable<int> groupId, Nullable<System.DateTime> startDate, Nullable<System.DateTime> endDate)
        {
            var groupIdParameter = groupId.HasValue ?
                new ObjectParameter("GroupId", groupId) :
                new ObjectParameter("GroupId", typeof(int));
    
            var startDateParameter = startDate.HasValue ?
                new ObjectParameter("StartDate", startDate) :
                new ObjectParameter("StartDate", typeof(System.DateTime));
    
            var endDateParameter = endDate.HasValue ?
                new ObjectParameter("EndDate", endDate) :
                new ObjectParameter("EndDate", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_GetTop10ClientPivotSummary", groupIdParameter, startDateParameter, endDateParameter);
        }
    
        public virtual ObjectResult<usp_GetMenuNew_Result> usp_GetMenuNew(Nullable<int> uID)
        {
            var uIDParameter = uID.HasValue ?
                new ObjectParameter("UID", uID) :
                new ObjectParameter("UID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_GetMenuNew_Result>("usp_GetMenuNew", uIDParameter);
        }
    
        public virtual int Revenue_report_new(Nullable<System.DateTime> startDate, Nullable<System.DateTime> endDate, Nullable<bool> supp, string publicationList, string mainCategoryList, string subCategoryList)
        {
            var startDateParameter = startDate.HasValue ?
                new ObjectParameter("StartDate", startDate) :
                new ObjectParameter("StartDate", typeof(System.DateTime));
    
            var endDateParameter = endDate.HasValue ?
                new ObjectParameter("EndDate", endDate) :
                new ObjectParameter("EndDate", typeof(System.DateTime));
    
            var suppParameter = supp.HasValue ?
                new ObjectParameter("Supp", supp) :
                new ObjectParameter("Supp", typeof(bool));
    
            var publicationListParameter = publicationList != null ?
                new ObjectParameter("PublicationList", publicationList) :
                new ObjectParameter("PublicationList", typeof(string));
    
            var mainCategoryListParameter = mainCategoryList != null ?
                new ObjectParameter("MainCategoryList", mainCategoryList) :
                new ObjectParameter("MainCategoryList", typeof(string));
    
            var subCategoryListParameter = subCategoryList != null ?
                new ObjectParameter("SubCategoryList", subCategoryList) :
                new ObjectParameter("SubCategoryList", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Revenue_report_new", startDateParameter, endDateParameter, suppParameter, publicationListParameter, mainCategoryListParameter, subCategoryListParameter);
        }
    
        public virtual int Revenue_report_new4(Nullable<System.DateTime> startDate, Nullable<System.DateTime> endDate, Nullable<bool> supp, string publicationList, string mainCategoryList, string subCategoryList)
        {
            var startDateParameter = startDate.HasValue ?
                new ObjectParameter("StartDate", startDate) :
                new ObjectParameter("StartDate", typeof(System.DateTime));
    
            var endDateParameter = endDate.HasValue ?
                new ObjectParameter("EndDate", endDate) :
                new ObjectParameter("EndDate", typeof(System.DateTime));
    
            var suppParameter = supp.HasValue ?
                new ObjectParameter("Supp", supp) :
                new ObjectParameter("Supp", typeof(bool));
    
            var publicationListParameter = publicationList != null ?
                new ObjectParameter("PublicationList", publicationList) :
                new ObjectParameter("PublicationList", typeof(string));
    
            var mainCategoryListParameter = mainCategoryList != null ?
                new ObjectParameter("MainCategoryList", mainCategoryList) :
                new ObjectParameter("MainCategoryList", typeof(string));
    
            var subCategoryListParameter = subCategoryList != null ?
                new ObjectParameter("SubCategoryList", subCategoryList) :
                new ObjectParameter("SubCategoryList", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Revenue_report_new4", startDateParameter, endDateParameter, suppParameter, publicationListParameter, mainCategoryListParameter, subCategoryListParameter);
        }
    
        public virtual int Revenue_report_CM(Nullable<System.DateTime> startDate, Nullable<System.DateTime> endDate, Nullable<bool> supp, string publicationList, string mainCategoryList, string subCategoryList)
        {
            var startDateParameter = startDate.HasValue ?
                new ObjectParameter("StartDate", startDate) :
                new ObjectParameter("StartDate", typeof(System.DateTime));
    
            var endDateParameter = endDate.HasValue ?
                new ObjectParameter("EndDate", endDate) :
                new ObjectParameter("EndDate", typeof(System.DateTime));
    
            var suppParameter = supp.HasValue ?
                new ObjectParameter("Supp", supp) :
                new ObjectParameter("Supp", typeof(bool));
    
            var publicationListParameter = publicationList != null ?
                new ObjectParameter("PublicationList", publicationList) :
                new ObjectParameter("PublicationList", typeof(string));
    
            var mainCategoryListParameter = mainCategoryList != null ?
                new ObjectParameter("MainCategoryList", mainCategoryList) :
                new ObjectParameter("MainCategoryList", typeof(string));
    
            var subCategoryListParameter = subCategoryList != null ?
                new ObjectParameter("SubCategoryList", subCategoryList) :
                new ObjectParameter("SubCategoryList", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Revenue_report_CM", startDateParameter, endDateParameter, suppParameter, publicationListParameter, mainCategoryListParameter, subCategoryListParameter);
        }
    
        public virtual ObjectResult<usp_GetMenuInfo_Result> usp_GetMenuInfo(Nullable<int> uID)
        {
            var uIDParameter = uID.HasValue ?
                new ObjectParameter("UID", uID) :
                new ObjectParameter("UID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_GetMenuInfo_Result>("usp_GetMenuInfo", uIDParameter);
        }
    
        public virtual int Revenue_report_CM_client(Nullable<System.DateTime> startDate, Nullable<System.DateTime> endDate, Nullable<bool> supp, string publicationList, string mainCategoryList, string subCategoryList)
        {
            var startDateParameter = startDate.HasValue ?
                new ObjectParameter("StartDate", startDate) :
                new ObjectParameter("StartDate", typeof(System.DateTime));
    
            var endDateParameter = endDate.HasValue ?
                new ObjectParameter("EndDate", endDate) :
                new ObjectParameter("EndDate", typeof(System.DateTime));
    
            var suppParameter = supp.HasValue ?
                new ObjectParameter("Supp", supp) :
                new ObjectParameter("Supp", typeof(bool));
    
            var publicationListParameter = publicationList != null ?
                new ObjectParameter("PublicationList", publicationList) :
                new ObjectParameter("PublicationList", typeof(string));
    
            var mainCategoryListParameter = mainCategoryList != null ?
                new ObjectParameter("MainCategoryList", mainCategoryList) :
                new ObjectParameter("MainCategoryList", typeof(string));
    
            var subCategoryListParameter = subCategoryList != null ?
                new ObjectParameter("SubCategoryList", subCategoryList) :
                new ObjectParameter("SubCategoryList", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Revenue_report_CM_client", startDateParameter, endDateParameter, suppParameter, publicationListParameter, mainCategoryListParameter, subCategoryListParameter);
        }
    
        public virtual ObjectResult<contactreport_visit_Result> contactreport_visit(string user_Id)
        {
            var user_IdParameter = user_Id != null ?
                new ObjectParameter("User_Id", user_Id) :
                new ObjectParameter("User_Id", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<contactreport_visit_Result>("contactreport_visit", user_IdParameter);
        }
    }
}
