//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AMR
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrganizationChartBI
    {
        public int Id { get; set; }
        public string User_id { get; set; }
        public string Report_to_user_id { get; set; }
        public string Title { get; set; }
        public Nullable<bool> Root { get; set; }
        public System.Guid rowguid { get; set; }
    }
}
