//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AMR
{
    using System;
    using System.Collections.Generic;
    
    public partial class RateCardDetail
    {
        public int Rate_Id { get; set; }
        public Nullable<int> Sub_Category { get; set; }
        public string City_edition { get; set; }
        public Nullable<float> Full_Rate { get; set; }
        public Nullable<float> Half_Rate { get; set; }
        public string WeekDay { get; set; }
        public Nullable<float> Full_Rate_day { get; set; }
        public Nullable<float> Half_Rate_day { get; set; }
        public int Id { get; set; }
    
        public virtual RateCard RateCard { get; set; }
        public virtual RateCard RateCard1 { get; set; }
    }
}
