//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AMR
{
    using System;
    using System.Collections.Generic;
    
    public partial class RatePolicy
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public RatePolicy()
        {
            this.RatePolicyStations = new HashSet<RatePolicyStation>();
        }
    
        public int ID { get; set; }
        public Nullable<int> Publication { get; set; }
        public Nullable<int> Main_Category { get; set; }
        public Nullable<int> Sub_category { get; set; }
        public Nullable<float> Rate { get; set; }
        public Nullable<byte> Page { get; set; }
        public Nullable<bool> Base_station { get; set; }
        public Nullable<float> Base_Rate { get; set; }
        public Nullable<byte> No_Station { get; set; }
        public Nullable<bool> Percentage { get; set; }
        public string Operator { get; set; }
        public string WeekDay { get; set; }
        public Nullable<float> Rate_day { get; set; }
        public Nullable<byte> cExport { get; set; }
        public Nullable<byte> Size_exception { get; set; }
        public string Remarks { get; set; }
        public string Rec_add_by { get; set; }
        public Nullable<System.DateTime> rec_add_dateTime { get; set; }
        public string rec_edit_by { get; set; }
        public Nullable<System.DateTime> rec_edit_DateTime { get; set; }
        public System.Guid rowguid { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RatePolicyStation> RatePolicyStations { get; set; }
    }
}
