//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AMR
{
    using System;
    using System.Collections.Generic;
    
    public partial class TempAddMiss_1
    {
        public string brand_name { get; set; }
        public Nullable<int> brand { get; set; }
        public string agency_name { get; set; }
        public string client_name { get; set; }
        public string mSize_sum { get; set; }
        public Nullable<int> ActiveSize_sum { get; set; }
        public Nullable<int> non_active_sum { get; set; }
        public string pub_abreviation { get; set; }
        public Nullable<int> Gp_Id { get; set; }
        public Nullable<int> Half_2 { get; set; }
        public System.Guid rowguid { get; set; }
        public Nullable<int> Client_Visit { get; set; }
        public Nullable<int> Agency_Visit { get; set; }
        public string Visiter_Name { get; set; }
        public Nullable<int> Client_Visit_1 { get; set; }
        public Nullable<int> Agency_Visit_1 { get; set; }
    }
}
