//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AMR
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transaction_Dup
    {
        public int Id { get; set; }
        public Nullable<int> Loc_ID { get; set; }
        public Nullable<int> Orignal_ID { get; set; }
        public Nullable<System.DateTime> Publication_Date { get; set; }
        public string City_Edition { get; set; }
        public Nullable<int> Publication { get; set; }
        public Nullable<int> Page { get; set; }
        public Nullable<int> Main_Category { get; set; }
        public Nullable<int> Sub_Category { get; set; }
        public string Ad_Type { get; set; }
        public Nullable<int> Brand { get; set; }
        public Nullable<int> Client_Company { get; set; }
        public Nullable<int> Agency { get; set; }
        public string Caption { get; set; }
        public Nullable<int> Size_CM { get; set; }
        public string Size_Col { get; set; }
        public string Colour_BW { get; set; }
        public string Rec_Added_By { get; set; }
        public Nullable<System.DateTime> Rec_Added_Date { get; set; }
        public Nullable<System.DateTime> Rec_Added_Time { get; set; }
        public string Rec_Edited_By { get; set; }
        public Nullable<System.DateTime> Rec_Edited_Date { get; set; }
        public Nullable<System.DateTime> Rec_Edited_Time { get; set; }
        public bool cExport { get; set; }
        public Nullable<int> Col_Size { get; set; }
        public System.Guid rowguid { get; set; }
        public Nullable<int> Type_Id { get; set; }
        public string RO { get; set; }
    }
}
