//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AMR
{
    using System;
    using System.Collections.Generic;
    
    public partial class Type
    {
        public int Id { get; set; }
        public string Type1 { get; set; }
        public string Remarks { get; set; }
        public string add_by { get; set; }
        public Nullable<System.DateTime> Add_DateTime { get; set; }
        public string Edit_by { get; set; }
        public Nullable<System.DateTime> Edit_DateTime { get; set; }
    }
}
