//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AMR
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserSecurity
    {
        public string User_Id { get; set; }
        public int Control_Id { get; set; }
        public string Auth_Access { get; set; }
        public string Auth_Add { get; set; }
        public string Auth_Edit { get; set; }
        public string Auth_Del { get; set; }
        public string Auth_Print { get; set; }
        public bool cExport { get; set; }
        public System.Guid rowguid { get; set; }
    
        public virtual SecurityControl SecurityControl { get; set; }
        public virtual User User { get; set; }
    }
}
