//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AMR
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public User()
        {
            this.DailyRevenues = new HashSet<DailyRevenue>();
            this.MonthlyTargets = new HashSet<MonthlyTarget>();
            this.Organisations = new HashSet<Organisation>();
            this.OrgSecurities = new HashSet<OrgSecurity>();
            this.UserSecurities = new HashSet<UserSecurity>();
        }
    
        public string User_Id { get; set; }
        public string User_Name { get; set; }
        public string User_Pass { get; set; }
        public string User_Desig { get; set; }
        public Nullable<int> User_Groups { get; set; }
        public Nullable<byte> User_Level { get; set; }
        public string Rec_Added_By { get; set; }
        public Nullable<System.DateTime> Rec_Added_Date { get; set; }
        public Nullable<System.DateTime> Rec_Added_Time { get; set; }
        public string Rec_Edited_By { get; set; }
        public Nullable<System.DateTime> Rec_Edited_Date { get; set; }
        public Nullable<System.DateTime> Rec_Edited_Time { get; set; }
        public bool cExport { get; set; }
        public Nullable<bool> User_Active { get; set; }
        public int ID { get; set; }
        public Nullable<int> RoleId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DailyRevenue> DailyRevenues { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MonthlyTarget> MonthlyTargets { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Organisation> Organisations { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrgSecurity> OrgSecurities { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserSecurity> UserSecurities { get; set; }
    }
}
