//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CDSN
{
    using System;
    using System.Collections.Generic;
    
    public partial class bar2
    {
        public int ChannelId { get; set; }
        public string ChannelName { get; set; }
        public Nullable<int> South { get; set; }
        public Nullable<int> Center { get; set; }
        public Nullable<int> North { get; set; }
    }
}
