//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CDSN
{
    using System;
    using System.Collections.Generic;
    
    public partial class DBMunir2
    {
        public int OperatorId { get; set; }
        public int CityId { get; set; }
        public int TerritoryId { get; set; }
        public int DivisionId { get; set; }
        public string District { get; set; }
        public string City { get; set; }
        public string Operator { get; set; }
        public Nullable<int> E_E { get; set; }
        public Nullable<int> AD { get; set; }
        public Nullable<int> HUM { get; set; }
        public Nullable<int> Geo_Ent { get; set; }
        public Nullable<int> U1 { get; set; }
        public Nullable<int> AAN { get; set; }
        public Nullable<int> BOL_E { get; set; }
        public Nullable<int> AAJ_Ent { get; set; }
        public Nullable<int> ALIF { get; set; }
        public Nullable<int> A_ { get; set; }
        public Nullable<int> TV1 { get; set; }
        public Nullable<int> PTV_HOM { get; set; }
        public Nullable<int> A_Life { get; set; }
    }
}
