//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CDSN
{
    using System;
    using System.Collections.Generic;
    
    public partial class GoogleSubAreaMap
    {
        public int ID { get; set; }
        public Nullable<int> CountryId { get; set; }
        public Nullable<int> AreaId { get; set; }
        public Nullable<int> SubAreaId { get; set; }
        public double Lat { get; set; }
        public double Lng { get; set; }
        public string InfoWindowText { get; set; }
        public string IconImage { get; set; }
        public string IconShadow { get; set; }
        public Nullable<int> IconAnchor { get; set; }
        public Nullable<int> IconSize { get; set; }
        public Nullable<int> IconShadowSize { get; set; }
        public string InfoWindowAnchor { get; set; }
        public string Flag { get; set; }
    }
}
