//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CDSN
{
    using System;
    using System.Collections.Generic;
    
    public partial class NewsCPRTable2
    {
        public int OperatorId { get; set; }
        public int CityId { get; set; }
        public int TerritoryId { get; set; }
        public string District { get; set; }
        public string City { get; set; }
        public string Operator { get; set; }
        public Nullable<int> EXP_N { get; set; }
        public Nullable<int> GEO_N { get; set; }
        public Nullable<int> SAMMA { get; set; }
        public Nullable<int> ARY_N { get; set; }
        public Nullable<int> DUNYA { get; set; }
        public Nullable<int> DAWN { get; set; }
        public Nullable<int> S_TV_ { get; set; }
        public Nullable<int> C92_ { get; set; }
        public Nullable<int> C_24 { get; set; }
        public Nullable<int> BOL_N_ { get; set; }
        public Nullable<int> AAJ_N { get; set; }
        public Nullable<int> GNN { get; set; }
        public Nullable<int> NEO { get; set; }
        public Nullable<int> AT { get; set; }
        public Nullable<int> HUM_N { get; set; }
        public Nullable<int> CAPT { get; set; }
        public Nullable<int> PNN { get; set; }
        public Nullable<int> L_NEWS_ { get; set; }
    }
}
