//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CDSN
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblArea
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblArea()
        {
            this.tblSubAreas = new HashSet<tblSubArea>();
        }
    
        public int AreaId { get; set; }
        public int CityId { get; set; }
        public string AreaName { get; set; }
        public Nullable<System.DateTime> Rec_Added_Date { get; set; }
        public Nullable<int> Rec_Added_By { get; set; }
        public Nullable<System.DateTime> Rec_Edit_Date { get; set; }
        public Nullable<int> Rec_Edit_By { get; set; }
        public Nullable<bool> active { get; set; }
    
        public virtual tblCity tblCity { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblSubArea> tblSubAreas { get; set; }
    }
}
