//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CDSN
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblActivity
    {
        public int Id { get; set; }
        public int UserId { get; set; }
        public Nullable<System.DateTime> ActivityDate { get; set; }
        public string ActivityType { get; set; }
        public int SAId { get; set; }
        public int OperatorId { get; set; }
        public int ComplainId { get; set; }
        public int ConsumerId { get; set; }
        public string Remarks { get; set; }
        public int AssignedTo { get; set; }
        public string Status { get; set; }
        public string ComplainStatus { get; set; }
    
        public virtual tblUser tblUser { get; set; }
    }
}
