//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CDSN
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblCountry
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblCountry()
        {
            this.tblusercountries = new HashSet<tblusercountry>();
            this.tblOperatorInfoes = new HashSet<tblOperatorInfo>();
            this.tblRegions = new HashSet<tblRegion>();
        }
    
        public int CountryId { get; set; }
        public string CountryName { get; set; }
        public Nullable<System.DateTime> Rec_Added_Date { get; set; }
        public Nullable<int> Rec_Added_By { get; set; }
        public Nullable<System.DateTime> Rec_Edit_Date { get; set; }
        public Nullable<int> Rec_Edit_By { get; set; }
        public Nullable<bool> active { get; set; }
        public Nullable<int> Seq { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblusercountry> tblusercountries { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblOperatorInfo> tblOperatorInfoes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblRegion> tblRegions { get; set; }
    }
}
