//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CDSN
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblChannelPosition
    {
        public int Id { get; set; }
        public int OperatorId { get; set; }
        public int ChannelId { get; set; }
        public Nullable<int> CurPosition { get; set; }
        public Nullable<int> PrevPosition { get; set; }
        public Nullable<System.DateTime> WEF { get; set; }
        public Nullable<int> CreateBuy { get; set; }
    
        public virtual tblChannel tblChannel { get; set; }
    }
}
