//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CDSN
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblCity
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblCity()
        {
            this.tblAreas = new HashSet<tblArea>();
            this.UserInfoes = new HashSet<UserInfo>();
            this.tblOperators = new HashSet<tblOperator>();
            this.tblOperatorInfoes = new HashSet<tblOperatorInfo>();
            this.tblPropertiers = new HashSet<tblPropertier>();
        }
    
        public int Id { get; set; }
        public int DivisionId { get; set; }
        public string CityName { get; set; }
        public Nullable<int> SeqmentID { get; set; }
        public Nullable<int> Orderby { get; set; }
        public Nullable<System.DateTime> Rec_Added_Date { get; set; }
        public Nullable<int> Rec_Added_By { get; set; }
        public Nullable<System.DateTime> Rec_Edit_Date { get; set; }
        public Nullable<int> Rec_Edit_By { get; set; }
        public Nullable<bool> active { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblArea> tblAreas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserInfo> UserInfoes { get; set; }
        public virtual TblDivision TblDivision { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblOperator> tblOperators { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblOperatorInfo> tblOperatorInfoes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblPropertier> tblPropertiers { get; set; }
    }
}
