//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CDSN
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblChannelList
    {
        public string GEO { get; set; }
        public string SAMMA { get; set; }
        public string Ary { get; set; }
        public string Waqat { get; set; }
        public string GEOSports { get; set; }
        public string Express { get; set; }
        public string EXPIE { get; set; }
    }
}
