//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CDSN
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblChannel
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblChannel()
        {
            this.tblChannelHistories = new HashSet<tblChannelHistory>();
            this.tblChannelLogs = new HashSet<tblChannelLog>();
            this.tblChannelPositions = new HashSet<tblChannelPosition>();
            this.tblCPIS = new HashSet<tblCPI>();
        }
    
        public int Id { get; set; }
        public Nullable<int> TypeID { get; set; }
        public string ChannelName { get; set; }
        public string ShortName { get; set; }
        public bool IsActive { get; set; }
        public int OrderBy { get; set; }
        public Nullable<System.DateTime> Rec_Added_Date { get; set; }
        public Nullable<int> Rec_Added_By { get; set; }
        public Nullable<System.DateTime> Rec_Edit_Date { get; set; }
        public Nullable<int> Rec_Edit_By { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblChannelHistory> tblChannelHistories { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblChannelLog> tblChannelLogs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblChannelPosition> tblChannelPositions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblCPI> tblCPIS { get; set; }
    }
}
