//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CDSN
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblFilterControlDetail
    {
        public int FilterControlDetailId { get; set; }
        public int FilterControlId { get; set; }
        public string FieldCaption { get; set; }
        public string FieldAttributes { get; set; }
    
        public virtual tblFilterControl tblFilterControl { get; set; }
    }
}
