//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CDSN
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblIdctr
    {
        public int Id { get; set; }
        public string ForTable { get; set; }
        public int counter { get; set; }
    }
}
