//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CDSN
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblInventory
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblInventory()
        {
            this.tblInventoryIssues = new HashSet<tblInventoryIssue>();
        }
    
        public int Id { get; set; }
        public string ItemInfo { get; set; }
        public Nullable<System.DateTime> ReceiveDate { get; set; }
        public string TAG { get; set; }
        public string status { get; set; }
        public Nullable<System.DateTime> ReturnDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblInventoryIssue> tblInventoryIssues { get; set; }
    }
}
