//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CDSN
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblInventoryIssue
    {
        public int Id { get; set; }
        public int OperatorId { get; set; }
        public int InventoryId { get; set; }
        public Nullable<System.DateTime> IssueDate { get; set; }
    
        public virtual tblInventory tblInventory { get; set; }
    }
}
