//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CDSN
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblMenuItem
    {
        public int MenuItemId { get; set; }
        public int MenuHeaderId { get; set; }
        public int FormId { get; set; }
        public string MenuItemName { get; set; }
        public int UserId { get; set; }
    
        public virtual tblUser tblUser { get; set; }
    }
}
