//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CDSN
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblOperatorInfo
    {
        public int ID { get; set; }
        public int OperatorId { get; set; }
        public int CountryId { get; set; }
        public int RegionId { get; set; }
        public int TerritoryId { get; set; }
        public int DivisionId { get; set; }
        public int CityId { get; set; }
        public int AreaId { get; set; }
        public Nullable<int> SubAreaId { get; set; }
        public Nullable<int> Subscribers { get; set; }
        public Nullable<System.DateTime> WEF { get; set; }
        public Nullable<System.DateTime> Rec_Added_Date { get; set; }
        public Nullable<int> Rec_Added_By { get; set; }
        public Nullable<System.DateTime> Rec_Edit_Date { get; set; }
        public Nullable<int> Rec_Edit_By { get; set; }
    
        public virtual tblCity tblCity { get; set; }
        public virtual tblCountry tblCountry { get; set; }
        public virtual TblDivision TblDivision { get; set; }
        public virtual tblOperator tblOperator { get; set; }
        public virtual tblOperatorInfo tblOperatorInfo1 { get; set; }
        public virtual tblOperatorInfo tblOperatorInfo2 { get; set; }
        public virtual tblRegion tblRegion { get; set; }
        public virtual tblTerritory tblTerritory { get; set; }
    }
}
