//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CDSN
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblScheduleActivity
    {
        public int Id { get; set; }
        public int UserId { get; set; }
        public string Description { get; set; }
        public int TaskId { get; set; }
    
        public virtual tblTaskActivity tblTaskActivity { get; set; }
        public virtual tblUser tblUser { get; set; }
    }
}
