//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CDSN
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblTerritory
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblTerritory()
        {
            this.tblContacts = new HashSet<tblContact>();
            this.TblDivisions = new HashSet<TblDivision>();
            this.tblOperatorInfoes = new HashSet<tblOperatorInfo>();
            this.tblUserTerritories = new HashSet<tblUserTerritory>();
        }
    
        public int Id { get; set; }
        public Nullable<int> RegionId { get; set; }
        public string TerritoryName { get; set; }
        public string ShortNames { get; set; }
        public Nullable<bool> active { get; set; }
        public Nullable<System.DateTime> Rec_Added_Date { get; set; }
        public Nullable<int> Rec_Added_By { get; set; }
        public Nullable<System.DateTime> Rec_Edit_Date { get; set; }
        public Nullable<int> Rec_Edit_By { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblContact> tblContacts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblDivision> TblDivisions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblOperatorInfo> tblOperatorInfoes { get; set; }
        public virtual tblRegion tblRegion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblUserTerritory> tblUserTerritories { get; set; }
    }
}
