//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CDSN
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblUserHeadend
    {
        public int ID { get; set; }
        public int UserId { get; set; }
        public int HeadendID { get; set; }
    
        public virtual tblOperator tblOperator { get; set; }
        public virtual tblUser tblUser { get; set; }
    }
}
