//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ABMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class CategoryWorkingExperience
    {
        public int ID { get; set; }
        public int WorkingExperienceID { get; set; }
        public int MasterID { get; set; }
    
        public virtual MasterTable MasterTable { get; set; }
        public virtual WorkingExperience WorkingExperience { get; set; }
    }
}
