//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ABMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class DegreeInfo
    {
        public DegreeInfo()
        {
            this.AcademicQualifications = new HashSet<AcademicQualification>();
        }
    
        public int ID { get; set; }
        public string DegreeName { get; set; }
        public string EdLevel { get; set; }
    
        public virtual ICollection<AcademicQualification> AcademicQualifications { get; set; }
    }
}
