//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ABMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class Role
    {
        public Role()
        {
            this.RolesItems = new HashSet<RolesItem>();
            this.Userdbs = new HashSet<Userdb>();
        }
    
        public int ID { get; set; }
        public string UserRole { get; set; }
        public bool IsActive { get; set; }
    
        public virtual ICollection<RolesItem> RolesItems { get; set; }
        public virtual ICollection<Userdb> Userdbs { get; set; }
    }
}
