//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ABMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class vGNBData
    {
        public string Category { get; set; }
        public string PositionName { get; set; }
        public string Experience { get; set; }
        public string Location { get; set; }
        public string ReadytoJoinID { get; set; }
        public string ApplicantName { get; set; }
        public bool Married { get; set; }
        public string ApplicantAddress { get; set; }
        public string City { get; set; }
        public string EmailID { get; set; }
        public bool Gender { get; set; }
        public string Mobile { get; set; }
        public string LandLine { get; set; }
        public System.DateTime DOB { get; set; }
        public string PlaceofBirth { get; set; }
        public Nullable<System.DateTime> ApplicationDate { get; set; }
        public string AcademicInstitute { get; set; }
        public string PassingYear { get; set; }
        public string DegreeName { get; set; }
        public string CompanyName { get; set; }
        public string PositioninCompany { get; set; }
        public Nullable<int> Duration_in_days { get; set; }
        public Nullable<System.DateTime> FromDate { get; set; }
        public Nullable<System.DateTime> ToDate { get; set; }
        public Nullable<int> Duration { get; set; }
        public string TrainingName { get; set; }
        public string InstituteName { get; set; }
        public string TrgDuration { get; set; }
        public string TrgYear { get; set; }
        public string Technical_Inistitute { get; set; }
        public string Technical_Degree { get; set; }
        public string Technical_Qualification_Passing_Year { get; set; }
    }
}
