//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ABMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class vUserDepartmentPosition
    {
        public int UserID { get; set; }
        public int DepartmentID { get; set; }
        public int PositionID { get; set; }
        public string PositionName { get; set; }
    }
}
