//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ABMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class WorkExperience
    {
        public int ID { get; set; }
        public int RecordID { get; set; }
        public string CompanyName { get; set; }
        public string PositioninCompany { get; set; }
        public System.DateTime FromDate { get; set; }
        public System.DateTime ToDate { get; set; }
        public int Duration { get; set; }
        public string BriefDescription { get; set; }
    
        public virtual MasterTable MasterTable { get; set; }
    }
}
